<?php

$bounceArray=array();
$emailFound=array();
$distroFound=array();
$noEmail=array();
$noDistro=array();
$autoreplyFound=array();
$autoreplyNone=array();
$attachments=array();
$safeAttach=array();
$unsafeAttach=array();
$badSubjects=array();
$okSubjects=array();
$hasRE=array();
$noRE=array();
$noTo=array();
$noFrom=array();
$hasFeedback=array();
$noFeedback=array();
$hasReplyTo=array();
$noReplyTo=array();
$inbox=array();
$spam=array();
$safemail=array();
$reviewmail=array();
$junkmail=array();